### ISSUE TITLE
Interactive book

### ISSUE THREAD

**Issue by davidjabon** [sr258/scorm-h5p-wrapper#10]
I have not been able to get the wrapper to wrap the content type "interactive book" in a SCORM.  It produces a blank page. Looking at the html, it seems to not incorporate the libraries.  Is this a known limitation?

**Comment by johnnyjo04** [comment]
@davidjabon I am having the same issue as well. I can't get the "interactive book" in SCORM to appear. I keep getting a blank page. It works with the other options such as "interactive video" or "course presentation", but not with the "interactive book". I was really hoping to see if there was anyway to convert the H5P file into a SCORM file if the file was an interactive book. Any ideas??

**Comment by sr258** [comment]
Please try Lumi 0.8.1 (https://lumi.education), which also has a SCORM export and I fixed this bug there.

**Comment by johnnyjo04** [comment]
Hi @sr258, you are awesome! Thank you for the response. I just tried it and the interactive book worked! The only bug or issue that I found was that youtube videos dont appear on the pages. It just says "video player loading". Any thoughts?

**Comment by sr258** [comment]
Can you please open the developer console (see [here](https://balsamiq.com/support/faqs/browserconsole/) how to do it for your browser) before you open the content. Then open the content and check what errors you can see in the console. Post a screenshot here and I'll have a look what's wrong.

**Comment by johnnyjo04** [comment]
@sr258, please take a look at the screenshots below. I forgot to mention that I am using Google Chrome as my browser. 
![Before](https://user-images.githubusercontent.com/88908761/129783657-18980d6c-0556-4d37-9653-805defdbb23a.PNG)
![After](https://user-images.githubusercontent.com/88908761/129783661-87873603-e060-4f6f-81dc-621209b69c60.PNG)

**Comment by sr258** [comment]
The error is rather cryptic... My guess at the moment is that this is caused some cross origin request sharing issue. Can you send me the .h5p and .zip file with the scorm package to sr@lumi.education for further debugging? Otherwise It's difficult to tell the exact cause.

**Comment by johnnyjo04** [comment]
Got it, that makes sense. I just sent it over to your email. Thanks again! @sr258

**Comment by sr258** [comment]
I've identified the problem and it will require a bugfix release of Lumi (and before that the underlying h5p-nodejs-library). Give it a few more hours, until the CI pipelines are through and I'll release it.

**Comment by johnnyjo04** [comment]
@sr258 You've been so helpful! Thank you so much! :)
