### ISSUE TITLE
Concerning GDPR Healthcare

### ISSUE THREAD

**Issue by PhilRMCD** [sr258/scorm-h5p-wrapper#20]
Good day, 

I am working for a company in healtcare. I am a normal support technician who was asked to "Are we allowed to use this software in concerns of GDPR and personal data of patients ?" Because I dont know, what this software is for, what data you process during transformation etc, I am going to ask you. What data is processed, what is kept for how long, what are you able to see?

Yours faithfully 
Philipp

**Comment by sr258** [comment]
Hi,

there is a privacy policy on the running version: https://translate-h5p.tk/scorm-h5p/ (at the bottom). It gives you information about the data that is processed.

If you host the app yourself, no data is transmitted to anyone else, all data stays on the server. Your users can also use Lumi (https://lumi.education) to create SCORM files, which keeps all data on the user's local machine.

**Comment by PhilRMCD** [comment]
Citation:"H5P content you upload is only stored temporarily on our servers and deleted after the file has been packaged." - Can you proof that this happens automatically?

**Comment by sr258** [comment]
How should I prove this? Without access to the server you won't be able to check this and I of course server access is out of the question. The only way to be sure is to run the server yourself.

As I've said Lumi (which I also develop) has the same (and even better an improved) functionality and it keeps all files on the local machine.

**Comment by PhilRMCD** [comment]
> How should I prove this? 
For example with a screenshot, that pictures the corresponding code snippet

**Comment by sr258** [comment]
The files are deleted here:

https://github.com/sr258/scorm-h5p-wrapper/blob/3e7755ab4f0d39f33b9700adb2bd3ffa173b4996/src/index.js#L88
https://github.com/sr258/scorm-h5p-wrapper/blob/3e7755ab4f0d39f33b9700adb2bd3ffa173b4996/src/index.js#L124
https://github.com/sr258/scorm-h5p-wrapper/blob/3e7755ab4f0d39f33b9700adb2bd3ffa173b4996/src/index.js#L136

**Comment by PhilRMCD** [comment]
Thank you for your time and help. Really appreciated! #closed
